### ISSUE TITLE
Runtime error in assemble step

### ISSUE THREAD

**Issue by lamevan** [EichlerLab/smrtsv2#28] opened 2019-04-09 04:14 UTC
Hi,I run the assemble step and occur a error..
Could you please explain why I am getting error here?
Thank you..
[Tue Apr  9 11:32:20 2019]
rule assemble_polish:
    input: region/Chr3-13380000-60000/asm/contigs.fasta, region/Chr3-13380000-60000/asm/contigs.fasta.fai, region/Chr3-13380000-60000/asm/contig_aligned_reads.bam, region/Chr3-13380000-60000/asm/contig_aligned_reads.bam.pbi
    output: region/Chr3-13380000-60000/asm/contigs_polished.fasta
    jobid: 690
    wildcards: region_id=Chr3-13380000-60000
    resources: threads=4

ESC[33mJob counts:
        count   jobs
        1       assemble_polish
        1ESC[0m
'FRAMERATEHZ'
Traceback (most recent call last):
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/GenomicConsensus/main.py", line 258, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2746, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1994, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 461, in __init__
    self.updateCounts()
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2574, in updateCounts
    self.assertIndexed()
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2404, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1951, in _assertIndexed
    self._openFiles()
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2075, in _openFiles
    resource = IndexedBamReader(location)
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 374, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 183, in __init__
    self._loadReadGroupInfo()
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 95, in _loadReadGroupInfo
    rgFrameRate = ds["FRAMERATEHZ"]
KeyError: 'FRAMERATEHZ'
[ERROR] 'FRAMERATEHZ'
Traceback (most recent call last):
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/GenomicConsensus/main.py", line 258, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2746, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1994, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 461, in __init__
    self.updateCounts()
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2574, in updateCounts
    self.assertIndexed()
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2404, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1951, in _assertIndexed
    self._openFiles()
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2075, in _openFiles
    resource = IndexedBamReader(location)
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 374, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 183, in __init__
    self._loadReadGroupInfo()
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/pacbio/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 95, in _loadReadGroupInfo
    rgFrameRate = ds["FRAMERATEHZ"]
KeyError: 'FRAMERATEHZ'
ESC[32m[Tue Apr  9 11:32:21 2019]ESC[0m
ESC[31mError in rule assemble_polish:ESC[0m
ESC[31m    jobid: 0ESC[0m
ESC[31m    output: region/Chr3-13380000-60000/asm/contigs_polished.fastaESC[0m
ESC[31mESC[0m
ESC[31mRuleException:
CalledProcessError in line 250 of /home/linpeifan/smrtsv2/smrtsv2-master/rules/assemble_group.snakefile:
Command ' set -euo pipefail;  pb_python2 -s /home/linpeifan/smrtsv2/smrtsv2-master/dep/bin/variantCaller --referenceFilename region/Chr3-13380000-60000/asm/contigs.fasta region/Chr3-13380000-60000/asm/contig_aligned_reads.bam -o region/Chr3-13380000-60000/asm/contigs_polished.fasta -j 4 --algorithm=arrow; ' returned non-zero exit status 2.
  File "/home/linpeifan/smrtsv2/smrtsv2-master/rules/assemble_group.snakefile", line 250, in __rule_assemble_polish
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/python3/lib/python3.6/concurrent/futures/thread.py", line 55, in runESC[0m
ESC[31mExiting because a job execution failed. Look above for error messageESC[0m
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/linpeifan/temp/asm_group_gr-Chr3-13000000-1000000/.snakemake/log/2019-04-09T112437.712925.snakemake.log

**Comment by paudano** [comment] 2019-04-09 13:18
I am pretty sure this is caused by running from BAX files and not subread BAM files. When version 2 was released, we did not know how detrimental this would be to downstream tools. We just added a new section to `README.md` ("Creating the input FOFN file"). Pull the updated code and see that section. If it was run from BAX files, you will need to re-run SMRT-SV from the start.

**Comment by lamevan** [comment] 2019-04-11 09:43
hi,I have input the subread bam file instead of bax file.It works but another error occur.
[Wed Apr 10 16:54:12 2019]
rule assemble_align_fixup:
    input: region/Chr11-29000000-21106/asm/contig.sam, /home/linpeifan/r1nbsv/align/alignments.fofn, /home/linpeifan/r1nbsv/reference/ref.fasta, group/reads.bam
    output: region/Chr11-29000000-21106/asm/contig_fixup.bam
    jobid: 1
    wildcards: region_id=Chr11-29000000-21106
    resources: threads=1

ESC[33mJob counts:
        count   jobs
        1       assemble_align_fixup
        1ESC[0m
bamleftalign: /home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/tools/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by bamleftalign)
bamleftalign: /home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/tools/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by bamleftalign)
bamleftalign: /home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/tools/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by bamleftalign)
ESC[32m[Wed Apr 10 16:54:35 2019]ESC[0m
ESC[31mError in rule assemble_align_fixup:ESC[0m
ESC[31m    jobid: 0ESC[0m
ESC[31m    output: region/Chr11-29000000-21106/asm/contig_fixup.bamESC[0m
ESC[31mESC[0m
ESC[31mRuleException:
CalledProcessError in line 108 of /home/linpeifan/smrtsv2/smrtsv2-master/rules/assemble_group.snakefile:
Command ' set -euo pipefail;  mkdir -p $(dirname temp/region/Chr11-29000000-21106/asm/assemble_align_fixup); alignfixup -i region/Chr11-29000000-21106/asm/contig.sam -d $(head -n 1 /home/linpeifan/r1nbsv/align/alignments.fofn) -r /home/linpeifan/r1nbsv/reference/ref.fasta -g Chr11-29000000-21106 -o temp/region/Chr11-29000000-21106/asm/assemble_align_fixup_usort.bam; tlenadd -i temp/region/Chr11-29000000-21106/asm/assemble_align_fixup_usort.bam -o temp/region/Chr11-29000000-21106/asm/assemble_align_fixup_tlen.bam -r /home/linpeifan/r1nbsv/reference/ref.fasta; rm temp/region/Chr11-29000000-21106/asm/assemble_align_fixup_usort.bam; { samtools view -H temp/region/Chr11-29000000-21106/asm/assemble_align_fixup_tlen.bam | grep -Ev '^@(RG|PG)'; samtools view temp/region/Chr11-29000000-21106/asm/assemble_align_fixup_tlen.bam; } | bamleftalign -f /home/linpeifan/r1nbsv/reference/ref.fasta | samtools sort -T temp/region/Chr11-29000000-21106/asm/assemble_align_fixup -o region/Chr11-29000000-21106/asm/contig_fixup.bam; rm temp/region/Chr11-29000000-21106/asm/assemble_align_fixup_tlen.bam ' returned non-zero exit status 1.
  File "/home/linpeifan/smrtsv2/smrtsv2-master/rules/assemble_group.snakefile", line 108, in __rule_assemble_align_fixup
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/python3/lib/python3.6/concurrent/futures/thread.py", line 55, in runESC[0m
ESC[31mExiting because a job execution failed. Look above for error messageESC[0m
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/linpeifan/tmp/asm_group_gr-Chr11-29000000-21106/.snakemake/log/2019-04-10T164153.540316.snakemake.log
Could you explain why this error occured?Thanks!

**Comment by paudano** [comment] 2019-04-11 15:18
It must be finding `bamleftalign` outside of SMRT-SV. The `bamleftalign` executable in SMRT-SV is compiled with gcc 4.9.0, and it doesn't have GLIBCXX_3.4.21 (latest supported C++ interface is GLIBCXX_3.4.19).

Two questions:
1) Is `bamleftalign` in `dep/bin`?
2) Are you running `smrtsv.py` or `smrtsv`?

**Comment by lamevan** [comment] 2019-04-13 10:20
1.yes 2.smrtsv
it seems works after I put another libstdc++.so.6 to the /lib directory and create an soft link..
But another error occured...[33mJob counts:
	count	jobs
	1	assemble_polish
	1[0m
Child process exited with exitcode=-7.  Aborting.
[ERROR] Child process exited with exitcode=-7.  Aborting.
Aborting
[ERROR] Aborting
[32m[Thu Apr 11 18:10:23 2019][0m
[31mError in rule assemble_polish:[0m
[31m    jobid: 0[0m
[31m    output: region/Chr7-28960000-60000/asm/contigs_polished.fasta[0m
[31m[0m
[31mRuleException:
CalledProcessError in line 250 of /home/linpeifan/smrtsv2/smrtsv2-master/rules/assemble_group.snakefile:
Command ' set -euo pipefail;  pb_python2 -s /home/linpeifan/smrtsv2/smrtsv2-master/dep/bin/variantCaller --referenceFilename region/Chr7-28960000-60000/asm/contigs.fasta region/Chr7-28960000-60000/asm/contig_aligned_reads.bam -o region/Chr7-28960000-60000/asm/contigs_polished.fasta -j 4 --algorithm=quiver; ' returned non-zero exit status 255.
  File "/home/linpeifan/smrtsv2/smrtsv2-master/rules/assemble_group.snakefile", line 250, in __rule_assemble_polish
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/python3/lib/python3.6/concurrent/futures/thread.py", line 55, in run[0m
[31mExiting because a job execution failed. Look above for error message[0m
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/linpeifan/tmp/asm_group_gr-Chr7-28000000-1000000/.snakemake/log/2019-04-10T164155.812110.snakemake.log

**Comment by lamevan** [comment] 2019-04-13 10:23
Another error occured in another job..
[33mJob counts:
	count	jobs
	1	assemble_align_org
	1[0m
[INFO] 2019-04-11T18:09:48 [blasr] started.
/usr/bin/bash: line 1: 22855 Bus error               blasr region/Chr12-7920000-60000/reads/reads.bam region/Chr12-7920000-60000/asm/contigs.fasta --bam --bestn 1 --unaligned /dev/null --out temp/region/Chr12-7920000-60000/reads/align_reads.bam --nproc 4
[32m[Thu Apr 11 18:10:13 2019][0m
[31mError in rule assemble_align_org:[0m
[31m    jobid: 0[0m
[31m    output: region/Chr12-7920000-60000/asm/contig_aligned_reads.bam, region/Chr12-7920000-60000/asm/contig_aligned_reads.bam.pbi[0m
[31m[0m
[31mRuleException:
CalledProcessError in line 286 of /home/linpeifan/smrtsv2/smrtsv2-master/rules/assemble_group.snakefile:
Command ' set -euo pipefail;  blasr region/Chr12-7920000-60000/reads/reads.bam region/Chr12-7920000-60000/asm/contigs.fasta --bam --bestn 1 --unaligned /dev/null --out temp/region/Chr12-7920000-60000/reads/align_reads.bam --nproc 4; samtools sort -O bam -T temp/region/Chr12-7920000-60000/reads/align_reads_slice -o region/Chr12-7920000-60000/asm/contig_aligned_reads.bam temp/region/Chr12-7920000-60000/reads/align_reads.bam; pbindex region/Chr12-7920000-60000/asm/contig_aligned_reads.bam; rm temp/region/Chr12-7920000-60000/reads/align_reads.bam ' returned non-zero exit status 135.
  File "/home/linpeifan/smrtsv2/smrtsv2-master/rules/assemble_group.snakefile", line 286, in __rule_assemble_align_org
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/python3/lib/python3.6/concurrent/futures/thread.py", line 55, in run[0m
[31mExiting because a job execution failed. Look above for error message[0m
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/linpeifan/tmp/asm_group_gr-Chr12-7000000-1000000/.snakemake/log/2019-04-10T164158.101764.snakemake.log

**Comment by paudano** [comment] 2019-04-17 03:58
I think something is not right about your install environment, but I don't know what it would be. You should not need to link "libstdc++.so.6" into the lib directory, it should find that if everything in `dep` is installed correctly. Conda builds binaries with RPATH to find their libraries (it's like LD_LIBRARY_PATH, but built into the executable). So if you have to supplement a library, then something is not right with the install.

Also, a bus error is likely a memory error. I think a binary is trying to use a library it is not compatible with.

I would start by rebuilding everything in `dep`. Go into `dep`, run `make clean`, then `make`. If any errors occur in the build process, let's start by troubleshooting those. After that, let's continue running and troubleshooting SMRT-SV.

**Comment by paudano** [comment] 2019-04-21 23:25
Let me know if you are able to rebuild dep and if that makes any difference.

**Comment by lamevan** [comment] 2019-04-22 08:55
I rebuilt the environment as you said,it works now.Now it goes to assemble step and takes a long time.I will wait for the result.Thank you!

**Comment by paudano** [comment] 2019-04-22 12:37
Great. If you run into a new issue, open a new case for that. Closing this one for now.

**Closed as completed by paudano** 2019-04-22 12:37 UTC
